### ISSUE TITLE
Serializing Error in RDFLIB

### ISSUE THREAD

**Issue by othub** [weso/rdfsync#13]
when serializing a graph containing 
`
@prefix ex: <http://www.purl.org/hercules/asio/core#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
ex:AdministrativePersonnel rdf:type owl:Class ;
                           rdfs:subClassOf  ex:HumanResource ;
                           owl:disjointWith ex:ResearchPersonnel .
`

The output of said graph is missing the **rdf** prefix

`@prefix rdf: <http://www.w3.org/19999/02/22-rdf-syntax-ns#> .`

and for example the rdf:type is transformed to `ex:AdministrativePersonnel a owl:Class `

**Comment by othub** [comment]
UPDATE 1: Apparently **rdf:type** is transformed to **a** in a ttl file. the rest works correctly. All i need now is figure out how to keep the original **rdf:type**.

**Comment by labra** [comment]
Notice that `a` is the same as `rdf:type`, it is just an abbreviation for it, so you probably don't need to worry about it.

**Comment by othub** [comment]
noted! thank you. the issue will be closed then
